apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    environement: {{ .Values.labels.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}
  type: {{ .Values.service.type }}