name: CI with Minikube

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup and start Minikube
        uses: ./.github/actions/minikube-setup

      - name: Build and validate Docker image
        run: |
          eval $(minikube docker-env)
          docker build -t csizmaziakiki/helloapp:latest .
          docker run csizmaziakiki/helloapp:latest /bin/sh -c "ls -al"

      - name: Deploy to prod Minikube with Helm
        uses: ./.github/actions/helm-deploy
        with:
          values-file: 'values-prod.yaml'
          namespace: 'prod'