name: CI with Minikube

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Docker image
        run: |
          docker build -t csizmaziakiki/helloapp:latest .

      - name: Validate Docker /helloapp contents
        run: |
          docker run csizmaziakiki/helloapp:latest /bin/sh -c "ls -al"

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          # curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          # chmod +x kubectl
          # sudo mv kubectl /usr/local/bin/

      - name: Install Minikube
        run: |
          curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
          # curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          # chmod +x minikube
          # sudo mv minikube /usr/local/bin/

      - name: Start Minikube (Docker driver)
        run: |
          minikube start --driver=docker --wait=all
          kubectl get nodes
      
      - name: Deploy to QA Minikube with Helm
        uses: ./.github/actions/helm-deploy
        with:
          values-file: 'values-qa.yaml'
          namespace: 'qa'

      - name: Deploy to prod Minikube with Helm
        uses: ./.github/actions/helm-deploy
        with:
          values-file: 'values-prod.yaml'
          namespace: 'prod'

      # unnecessary??
      - name: Run tests in cluster
        run: |
          kubectl create deployment hello-minikube --image=kicbase/echo-server:1.0
          kubectl expose deployment hello-minikube --type=NodePort --port=8080
          # kubectl get services hello-minikube
          # minikube service hello-minikube
          kubectl rollout status deployment/hello-minikube
          kubectl get svc hello-minikube
          # kubectl port-forward service/hello-minikube 7080:8080

      - name: Test external endpoint
        run: curl localhost:80/