name: Test the application before deployment

on:
  pull_request: 
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: ./build.sh

      - name: Run tests
        run: ./test.sh

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          # curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          # chmod +x kubectl
          # sudo mv kubectl /usr/local/bin/

      - name: Install Minikube
        run: |
          curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
          # curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          # chmod +x minikube
          # sudo mv minikube /usr/local/bin/

      - name: Start Minikube (Docker driver)
        run: |
          minikube start --driver=docker --wait=all
          kubectl get nodes

      - name: Build Docker image
        run: |
          eval $(minikube docker-env)
          docker build -t csizmaziakiki/helloapp:latest .

      - name: Validate Docker /helloapp contents
        run: |
          eval $(minikube docker-env)
          docker run csizmaziakiki/helloapp:latest /bin/sh -c "ls -al"
      
      - name: Deploy to QA Minikube with Helm
        uses: ./.github/actions/helm-deploy
        with:
          values-file: 'values-qa.yaml'
          namespace: 'qa'
